#!/usr/bin/env bash
set -euo pipefail

MAPFILE_PATH="${1:-./mapping.csv}"
UDEV_RULE="/etc/udev/rules.d/99-usb-serial-aliases.rules"

if [[ ! -f "$MAPFILE_PATH" ]]; then
  echo "❌ Mapping niet gevonden: $MAPFILE_PATH"
  exit 1
fi

echo "🔧 Genereer udev-regels uit $MAPFILE_PATH…"

TMP_ENTRIES="$(mktemp /tmp/entries.XXXXXX)"
> "$TMP_ENTRIES"

parse_line() {
  local line="$1"
  line="${line#"${line%%[![:space:]]*}"}"; line="${line%"${line##*[![:space:]]}"}"
  [[ -z "$line" || "${line:0:1}" == "#" ]] && return 1
  local norm; norm="$(echo "$line" | tr '\t' ',' | tr -s ' ' ',' )"
  local serial nice role
  serial="$(echo "$norm" | cut -d',' -f1)"
  nice="$(echo   "$norm" | cut -d',' -f2)"
  role="$(echo   "$norm" | cut -d',' -f3)"
  [[ -z "$serial" || -z "$nice" || -z "$role" ]] && return 1

  serial="$(echo "$serial" | tr -cd '[:alnum:]')"
  nice="$(echo "$nice" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_]/_/g')"
  role="$(echo "$role" | tr '[:upper:]' '[:lower:]')"
  [[ "$role" == "leader" || "$role" == "follower" ]] || return 1

  echo "$serial,$nice,$role"
  return 0
}

while IFS= read -r raw; do
  if parsed="$(parse_line "$raw")"; then
    echo "$parsed" >> "$TMP_ENTRIES"
  else
    [[ -n "$raw" && "${raw:0:1}" != "#" ]] && echo "⚠️  Overslaan: $raw" >&2
  fi
done < "$MAPFILE_PATH"

# Backup bestaand rules-bestand
if [[ -f "$UDEV_RULE" ]]; then
  sudo cp -a "$UDEV_RULE" "${UDEV_RULE}.bak.$(date +%Y%m%d-%H%M%S)"
  echo "🗂  Backup: ${UDEV_RULE}.bak.*"
fi

TMP_RULE="$(mktemp /tmp/udev.rules.XXXXXX)"
{
  echo "# Auto-generated by $0 on $(date)"
  echo "# Kolommen: SERIAL_SHORT,NICE_NAME,ROLE"
  echo "# Symlinks: /dev/tty_<nice>_<role> en /dev/tty_follower (voor role=follower)"
} > "$TMP_RULE"

while IFS= read -r ent; do
  IFS=',' read -r serial nice role <<<"$ent"
  if [[ "$role" == "follower" ]]; then
    echo "SUBSYSTEM==\"tty\", ENV{ID_BUS}==\"usb\", ENV{ID_SERIAL_SHORT}==\"$serial\", SYMLINK+=\"tty_${nice}_${role}\", SYMLINK+=\"tty_follower\"" >> "$TMP_RULE"
  else
    echo "SUBSYSTEM==\"tty\", ENV{ID_BUS}==\"usb\", ENV{ID_SERIAL_SHORT}==\"$serial\", SYMLINK+=\"tty_${nice}_${role}\", SYMLINK+=\"tty_leader\"" >> "$TMP_RULE"
  fi
done < "$TMP_ENTRIES"

echo "📝 Schrijf naar $UDEV_RULE…"
sudo mv "$TMP_RULE" "$UDEV_RULE"
sudo chown root:root "$UDEV_RULE"
sudo chmod 0644 "$UDEV_RULE"

echo "🔁 Udev reload + trigger…"
sudo udevadm control --reload
sudo udevadm trigger
