#!/usr/bin/env bash
set -euo pipefail

# ========= Config =========
CONDA_DIR="$HOME/miniconda3"
CONDA_ENV="lerobot"
MINICONDA_URL="https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh"
UDEV_RULE="/etc/udev/rules.d/99-usb-serial-aliases.rules"
# ==========================

usage() {
  cat <<'EOF'
Gebruik: ./setup_lerobot_conda_udev.sh <mapping.csv>

Mapping-bestand: CSV/TSV/space met per regel:
  SERIAL_SHORT, NICE_NAME, ROLE

ROLE: leader of follower (case-insensitive)
Voorbeeld:
  5A46084108,black,leader
  5AAF287935,black,follower

Symlinks die worden gemaakt:
  /dev/tty_<nice>_<role>   (bijv. /dev/tty_black_leader, /dev/tty_black_follower)
  /dev/follower            (voor elke follower-regel; bij meerdere followers
                            zal dit naar het laatst ge(her)plugde device wijzen)
EOF
}

[[ "${1:-}" == "-h" || "${1:-}" == "--help" || $# -ne 1 ]] && { usage; exit 1; }
MAPFILE_PATH="$1"
[[ -f "$MAPFILE_PATH" ]] || { echo "❌ Niet gevonden: $MAPFILE_PATH"; exit 1; }

ARCH="$(uname -m)"
[[ "$ARCH" == "aarch64" ]] || { echo "❌ Verwacht aarch64 (64-bit). Gevonden: $ARCH"; exit 1; }

# ---- 1) Miniconda installeren (idempotent) ----
if [[ -x "$CONDA_DIR/bin/conda" ]]; then
  echo "✅ Miniconda al aanwezig: $CONDA_DIR"
else
  echo "⬇️  Download Miniconda…"
  TMP_SH="$(mktemp /tmp/miniconda.XXXXXX.sh)"
  curl -fsSL "$MINICONDA_URL" -o "$TMP_SH"
  echo "🛠  Installeren naar $CONDA_DIR…"
  bash "$TMP_SH" -b -p "$CONDA_DIR"
  rm -f "$TMP_SH"
fi

# Conda in deze shell
# shellcheck disable=SC1091
source "$CONDA_DIR/etc/profile.d/conda.sh"

# ---- 2) Env 'lerobot' met Python 3.10 + lerobot ----
if conda env list | awk '{print $1}' | grep -qx "$CONDA_ENV"; then
  echo "✅ Conda env bestaat: $CONDA_ENV"
else
  echo "🧪 Maak env $CONDA_ENV (python=3.10)…"
  conda create -y -n "$CONDA_ENV" python=3.10
fi

echo "📦 pip install lerobot…"
conda activate "$CONDA_ENV"
pip install --upgrade pip
pip install lerobot[feetech]

# ---- 3) Udev rules genereren ----
echo "🔧 Genereer udev-regels uit $MAPFILE_PATH…"

TMP_ENTRIES="$(mktemp /tmp/entries.XXXXXX)"
> "$TMP_ENTRIES"

parse_line() {
  local line="$1"
  # trim
  line="${line#"${line%%[![:space:]]*}"}"; line="${line%"${line##*[![:space:]]}"}"
  [[ -z "$line" || "${line:0:1}" == "#" ]] && return 1
  # normaliseer scheiding: tabs en meerdere spaties -> komma
  local norm; norm="$(echo "$line" | tr '\t' ',' | tr -s ' ' ',' )"
  local serial nice role
  serial="$(echo "$norm" | cut -d',' -f1)"
  nice="$(echo   "$norm" | cut -d',' -f2)"
  role="$(echo   "$norm" | cut -d',' -f3)"
  [[ -z "$serial" || -z "$nice" || -z "$role" ]] && return 1

  # schoonmaken
  serial="$(echo "$serial" | tr -cd '[:alnum:]')"
  nice="$(echo "$nice" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_]/_/g')"
  role="$(echo "$role" | tr '[:upper:]' '[:lower:]')"
  [[ "$role" == "leader" || "$role" == "follower" ]] || return 1

  echo "$serial,$nice,$role"
  return 0
}

while IFS= read -r raw; do
  if parsed="$(parse_line "$raw")"; then
    echo "$parsed" >> "$TMP_ENTRIES"
  else
    [[ -n "$raw" && "${raw:0:1}" != "#" ]] && echo "⚠️  Overslaan: $raw" >&2
  fi
done < "$MAPFILE_PATH"

# Backup bestaand rules-bestand
if [[ -f "$UDEV_RULE" ]]; then
  sudo cp -a "$UDEV_RULE" "${UDEV_RULE}.bak.$(date +%Y%m%d-%H%M%S)"
  echo "🗂  Backup: ${UDEV_RULE}.bak.*"
fi

TMP_RULE="$(mktemp /tmp/udev.rules.XXXXXX)"
{
  echo "# Auto-generated by $0 on $(date)"
  echo "# Kolommen: SERIAL_SHORT,NICE_NAME,ROLE"
  echo "# Symlinks: /dev/tty_<nice>_<role> en /dev/tty_follower (voor role=follower)"
} > "$TMP_RULE"

# Per entry regels
while IFS= read -r ent; do
  IFS=',' read -r serial nice role <<<"$ent"
  # Altijd: tty_<nice>_<role>
  if [[ "$role" == "follower" ]]; then
    
    echo "SUBSYSTEM==\"tty\", ENV{ID_BUS}==\"usb\", ENV{ID_SERIAL_SHORT}==\"$serial\", SYMLINK+=\"tty_${nice}_${role}\", SYMLINK+=\"tty_follower\"" >> "$TMP_RULE"
  else
    echo "SUBSYSTEM==\"tty\", ENV{ID_BUS}==\"usb\", ENV{ID_SERIAL_SHORT}==\"$serial\", SYMLINK+=\"tty_${nice}_${role}\", SYMLINK+=\"tty_leader\" >> "$TMP_RULE"
  fi
done < "$TMP_ENTRIES"

# Schrijf rules
echo "📝 Schrijf naar $UDEV_RULE…"
sudo mv "$TMP_RULE" "$UDEV_RULE"
sudo chown root:root "$UDEV_RULE"
sudo chmod 0644 "$UDEV_RULE"

echo "🔁 Udev reload + trigger…"
sudo udevadm control --reload
sudo udevadm trigger

# ---- 4) Dialout-tip ----
if ! id -nG "$USER" | grep -qw dialout; the
